Задание 14 / Коммит 1
htmlacademy-react/1553529-six-cities-5 pull request #8
Opened 2020-11-08 12:59 UTC by lehazyo

2020-11-09 02:00 UTC, tsapko3628 requested changes

2020-11-15 22:54 UTC, lehazyo commented on src/components/app/App.jsx
>  import Sign from "../Sign/Sign";
Тут ничего не могу сказать, в репозитории и у меня на компьютере один App/App.jsx
(если я правильно понял, что речь о том, что в пул реквесте есть файлы app/App.jsx и App/App.jsx

2020-11-17 17:40 UTC, tsapko3628 commented on src/components/app/App.jsx
>  import Sign from "../Sign/Sign";
возможно, если у тебя windows или macos (с файловой системой не чувствительной к регистру), у тебя может быть закомичена в репозитории одна версия, ты перемеменовал, закомитил и в репозитории появилась вторая, но ты не видишь её, потому что твоя файловая система не может их отличить. Удали не нужную версию через гитхаб

2020-11-17 17:52 UTC, tsapko3628 approved these changes

2020-11-17 17:52 UTC, tsapko3628 commented on src/components/App/App.jsx
> +});
а зачем эти props-ы, если компонент App их не принимает и, соответственно, не использует?

2020-11-17 17:52 UTC, tsapko3628 commented on src/components/Cities/Cities.jsx
> +        latitude: PropTypes.number,
nit: Обычно такие большие объекты (скорее всего они ещё и переиспользоваться будут) выносят в отдельный файл. Сейчас норм, но потом желательно вынести

2020-11-17 17:52 UTC, tsapko3628 commented on src/components/Main/Main.jsx
> +    coords: PropTypes.arrayOf(PropTypes.number)
вот об этом переиспользовании я и говорил в комментарии выше

2020-11-17 17:52 UTC, tsapko3628 commented on src/components/app/App.jsx
>  import Sign from "../Sign/Sign";
Причем в этом "дубле" всегда полная копия другого файла

2020-11-17 17:52 UTC, tsapko3628 commented on src/mocks/offers.json
> +    "images": [
не обязательно было делать такой большой файл) Надеюсь ты его не сам писал)

2020-11-23 14:08 UTC, merged